name: "LLM PR Reviewer Action"
description: "Review GitHub pull requests using an LLM."
author: "Brandon Saunders"
branding:
  icon: "eye"
  color: "blue"

inputs:
  openai_api_key:
    description: "Your OpenAI API key"
    required: true
  custom_prompt:
    description: "Optional custom prompt for the model"
    required: false

runs:
  using: "node20"
  main: "dist/app.js"
