name: "LLM PR Reviewer Action"
description: "Review GitHub pull requests using an LLM (OpenAI GPT-4 or other)."
author: "Brandon Saunders"
branding:
  icon: "eye"
  color: "blue"

inputs:
  openai_api_key:
    description: "Your OpenAI API key"
    required: true
  custom_prompt:
    description: "Optional custom prompt for the model"
    required: false
  openai_model:
    description: >
      OpenAI model to use (must be one of: gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-mini, o4-mini, o3-mini)
    required: false
    default: gpt-4.1

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install openai requests tiktoken
      shell: bash

    - name: Review PR with LLM
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
      run: python .github/scripts/review_pr.py
      shell: bash
