name: LLM PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: LLM PR Reviewer Action
        uses: SaundersB/llm-pr-reviewer-action@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
